import { mkdirSync, readFileSync, readdirSync, unlinkSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..', '..', '..');
const CLAUDE_MD = join(ROOT, 'CLAUDE.md');
const RULES_DIR = join(ROOT, '.cursor', 'rules');

const SECTION_MAP = [
  {
    match: /^## 1\.\s*中文输出/,
    file: 'proj-chinese.mdc',
    description: '中文输出规范',
    alwaysApply: true,
  },
  {
    match: /^## 2\.\s*方案完成后统一构建/,
    file: 'build-after-edit.mdc',
    description: '完成一轮代码、配置或构建脚本修改后必须统一执行构建',
    globs: 'src/**/*.ts,*.json,*.js',
  },
  {
    match: /^## 3\.\s*日志与调试约束/,
    file: 'logging-debug.mdc',
    description: '日志与调试信息必须走集中通道',
    globs: 'src/**/*.ts',
  },
  {
    match: /^## 4\.\s*平台同步修改/,
    file: 'platform-sync.mdc',
    description: 'Figma 与 MasterGo 适配器必须同步修改',
    globs: 'src/platform/**',
  },
  {
    match: /^## 5\.\s*九宫组件一致性/,
    file: 'component-consistency.mdc',
    description: '双平台九宫组件的区域、命名、约束和错误处理保持一致',
    globs: 'src/**/*.ts',
  },
  {
    match: /^## 6\.\s*Git 提交信息/,
    file: 'git-commit.mdc',
    description: 'Git 提交信息格式：单行英文 Conventional Commits',
    alwaysApply: true,
  },
  {
    match: /^## 7\.\s*代码检索路由/,
    file: 'code-intel-routing.mdc',
    description: '代码检索路由：结构走精确检索，概念走语义检索',
    globs: 'src/**',
  },
];

const GENERATED_TAG = '<!-- generated by sync-rules -->';

function splitSections(markdown) {
  const lines = markdown.split('\n');
  const sections = [];
  let current = null;

  for (const line of lines) {
    if (line.startsWith('## ')) {
      if (current) sections.push(current);
      current = { heading: line, body: [] };
    } else if (current) {
      current.body.push(line);
    }
  }

  if (current) sections.push(current);
  return sections;
}

function buildFrontmatter(config) {
  const lines = ['---'];
  lines.push(`description: "${config.description}"`);
  if (config.globs) {
    lines.push(`globs: ${config.globs}`);
    lines.push('alwaysApply: false');
  } else {
    lines.push('alwaysApply: true');
  }
  lines.push('---');
  return lines.join('\n');
}

function trimTrailingBlanks(text) {
  return text.replace(/\n{3,}/g, '\n\n').replace(/\n+$/, '\n');
}

function generate() {
  const markdown = readFileSync(CLAUDE_MD, 'utf8');
  const sections = splitSections(markdown);

  mkdirSync(RULES_DIR, { recursive: true });

  const generatedFiles = new Set();
  const results = [];

  for (const config of SECTION_MAP) {
    const section = sections.find((candidate) => config.match.test(candidate.heading));
    if (!section) {
      results.push(`  SKIP  ${config.file} (section not found)`);
      continue;
    }

    const title = section.heading.replace(/^## \d+\.\s*/, '# ');
    const body = trimTrailingBlanks(section.body.join('\n'));
    const content = [GENERATED_TAG, buildFrontmatter(config), '', title, '', body].join('\n');

    writeFileSync(join(RULES_DIR, config.file), content, 'utf8');
    generatedFiles.add(config.file);
    results.push(`  WRITE ${config.file}`);
  }

  for (const file of readdirSync(RULES_DIR).filter((name) => name.endsWith('.mdc'))) {
    if (generatedFiles.has(file)) continue;

    const path = join(RULES_DIR, file);
    const content = readFileSync(path, 'utf8');
    if (content.startsWith(GENERATED_TAG)) {
      unlinkSync(path);
      results.push(`  CLEAN ${file} (stale)`);
    }
  }

  console.log(`sync-rules: ${generatedFiles.size} files generated from CLAUDE.md`);
  for (const result of results) console.log(result);
}

generate();
